name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: 2060-io/organization/.github/workflows/2060-linter-call.yml@d199fdc55832f78f90158117a93d227709ca2746 # main
    with:
      enable-charts-lint: true
      charts-dir: charts
